version: 2.1
jobs:
  build:
    docker:
      - image: circleci/android:api-29-node8
    steps:
      - checkout
      - run: echo "Setup Flutter"
      - run:
          name: Install dependencies
          command: flutter pub get
      - run:
          name: Run tests
          command: flutter test
      - run:
          name: Build APK
          command: flutter build apk
      - persist_to_workspace:
          root: /
          paths:
            - build/
  deploy:
    docker:
      - image: circleci/android:api-29-node8
    steps:
      - attach_workspace:
          at: /
      - run:
          name: Deploy to Firebase
          command: |
            cd build/app/outputs/flutter-apk
            firebase appdistribution:distribute app-release.apk --app $FIREBASE_APP_ID --token $FIREBASE_TOKEN
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
